MINH_LIST_MEAN_DEAL_PROB =[
    ['user_id', 'deal_probability'],
    ['user_id', 'parent_category_name', 'deal_probability'],
    ['user_id', 'parent_category_name', 'category_name', 'deal_probability'],
    ['user_id', 'category_name', 'deal_probability'],
    ['user_type', 'deal_probability'],
    ['user_type', 'parent_category_name', 'deal_probability'],
    ['user_type', 'parent_category_name', 'category_name', 'deal_probability'],
    ['user_type', 'category_name', 'deal_probability'],
    ['region', 'deal_probability'],
    ['city', 'deal_probability'],
    ['region', 'deal_probability'],
    ['region', 'parent_category_name', 'deal_probability'],
    ['region', 'parent_category_name', 'category_name', 'deal_probability'],  
    ['city', 'deal_probability'],
    ['city', 'parent_category_name', 'deal_probability'],
    ['city', 'parent_category_name', 'category_name', 'deal_probability'], 
    ['city', 'user_type', 'deal_probability'],
    ['city', 'user_type', 'parent_category_name', 'deal_probability'],
    ['city', 'user_type', 'parent_category_name', 'category_name', 'deal_probability'],          
    ['region', 'user_type', 'deal_probability'],
    ['region', 'user_type', 'parent_category_name', 'deal_probability'],
    ['region', 'user_type', 'parent_category_name', 'category_name', 'deal_probability'],    
]

MINH_LIST_MEAN_PRICE = [
    ['user_id', 'deal_probability'],
    ['user_id', 'parent_category_name', 'deal_probability'],
    ['user_id', 'parent_category_name', 'category_name', 'deal_probability'],
    ['user_id', 'category_name', 'deal_probability'],
    ['user_type', 'deal_probability'],
    ['user_type', 'parent_category_name', 'deal_probability'],
    ['user_type', 'parent_category_name', 'category_name', 'deal_probability'],
    ['user_type', 'category_name', 'deal_probability'],
    ['region', 'deal_probability'],
    ['city', 'deal_probability'],
    ['region', 'deal_probability'],
    ['region', 'parent_category_name', 'deal_probability'],
    ['region', 'parent_category_name', 'category_name', 'deal_probability'],  
    ['city', 'deal_probability'],
    ['city', 'parent_category_name', 'deal_probability'],
    ['city', 'parent_category_name', 'category_name', 'deal_probability'], 
    ['city', 'user_type', 'deal_probability'],
    ['city', 'user_type', 'parent_category_name', 'deal_probability'],
    ['city', 'user_type', 'parent_category_name', 'category_name', 'deal_probability'],          
    ['region', 'user_type', 'deal_probability'],
    ['region', 'user_type', 'parent_category_name', 'deal_probability'],
    ['region', 'user_type', 'parent_category_name', 'category_name', 'deal_probability'],     
]

MINH_LIST_COUNT =[
    ['city', 'category_name'],
    ['region', 'category_name'],
]